// This file is auto-generated by @hey-api/openapi-ts

export type User = {
    id?: string;
    email: string;
    role?: 'admin' | 'teacher' | 'user';
    fullName?: string;
    dateOfBirth?: string;
    imagePath?: string;
    description?: string;
    academicTitle?: string;
    phoneNumber?: string;
    resetPasswordToken?: string;
    dateOfLastResetPasswordRequest?: string;
    note?: string;
};

export type Address = {
    id?: number;
    street?: string;
    houseNumber?: string;
    city: string;
    zipCode: string;
    note?: string;
    userId?: string;
};

export type Child = {
    id?: string;
    fullName: string;
    dateOfBirth: string;
    description?: string;
    monthlyFee: number;
    schoolDays: string;
    note?: string;
};

export type Sponsor = {
    id?: string;
    name?: string;
    imagePath?: string;
};

/**
 * (tsType: Omit<Sponsor, 'id' | 'imagePath'>, schemaOptions: { title: 'NewSponsor', exclude: [ 'id', 'imagePath' ] })
 */
export type NewSponsor = {
    name?: string;
};

/**
 * (tsType: SponsorWithRelations, schemaOptions: { includeRelations: true })
 */
export type SponsorWithRelations = {
    id?: string;
    name?: string;
    imagePath?: string;
};

export type Photo = {
    id?: string;
    existsFrom?: string;
    imagePath?: string;
    tag: 'ForestClub' | 'Places' | 'AdaptationProgram';
};

/**
 * (tsType: PhotoWithRelations, schemaOptions: { includeRelations: true })
 */
export type PhotoWithRelations = {
    id?: string;
    existsFrom?: string;
    imagePath?: string;
    tag: 'ForestClub' | 'Places' | 'AdaptationProgram';
};

export type Parenthood = {
    id?: string;
    userId: string;
    childId: string;
};

/**
 * (tsType: Omit<Parenthood, 'id'>, schemaOptions: { title: 'NewParenthood', exclude: [ 'id' ] })
 */
export type NewParenthood = {
    userId: string;
    childId: string;
};

export type GeneralInfo = {
    id?: number;
    title?: string;
    content?: string;
    page?: 'ForestClub' | 'AdaptationProgram' | 'Global';
    position?: number;
};

/**
 * (tsType: Omit<GeneralInfo, 'id'>, schemaOptions: { title: 'NewGeneralInfo', exclude: [ 'id' ] })
 */
export type NewGeneralInfo = {
    title?: string;
    content?: string;
    page?: 'ForestClub' | 'AdaptationProgram' | 'Global';
    position?: number;
};

/**
 * (tsType: GeneralInfoWithRelations, schemaOptions: { includeRelations: true })
 */
export type GeneralInfoWithRelations = {
    id?: number;
    title?: string;
    content?: string;
    page?: 'ForestClub' | 'AdaptationProgram' | 'Global';
    position?: number;
};

export type DayActivity = {
    id?: number;
    startTime: string;
    endTime: string;
    description?: string;
};

/**
 * (tsType: Omit<DayActivity, 'id'>, schemaOptions: { title: 'newDayActivity', exclude: [ 'id' ] })
 */
export type NewDayActivity = {
    startTime: string;
    endTime: string;
    description?: string;
};

/**
 * (tsType: DayActivityWithRelations, schemaOptions: { includeRelations: true })
 */
export type DayActivityWithRelations = {
    id?: number;
    startTime: string;
    endTime: string;
    description?: string;
};

export type ContactInfo = {
    id?: number;
    fullName: string;
    email: string;
    phoneNumber: string;
};

/**
 * (tsType: Omit<ContactInfo, 'id'>, schemaOptions: { title: 'newContactInfo', exclude: [ 'id' ] })
 */
export type NewContactInfo = {
    fullName: string;
    email: string;
    phoneNumber: string;
};

/**
 * (tsType: ContactInfoWithRelations, schemaOptions: { includeRelations: true })
 */
export type ContactInfoWithRelations = {
    id?: number;
    fullName: string;
    email: string;
    phoneNumber: string;
};

/**
 * (tsType: Omit<Child, 'id'>, schemaOptions: { title: 'NewChild', exclude: [ 'id' ] })
 */
export type NewChild = {
    fullName: string;
    dateOfBirth: string;
    description?: string;
    monthlyFee: number;
    schoolDays: string;
    note?: string;
};

/**
 * (tsType: UserCredentialsWithRelations, schemaOptions: { includeRelations: true })
 */
export type UserCredentialsWithRelations = {
    id?: string;
    password: string;
    userId: string;
};

/**
 * (tsType: AddressWithRelations, schemaOptions: { includeRelations: true })
 */
export type AddressWithRelations = {
    id?: number;
    street?: string;
    houseNumber?: string;
    city: string;
    zipCode: string;
    note?: string;
    userId?: string;
};

/**
 * (tsType: AttendanceWithRelations, schemaOptions: { includeRelations: true })
 */
export type AttendanceWithRelations = {
    id?: string;
    date: string;
    tag: 'normal' | 'alternative';
    pickUp?: boolean;
    childId?: string;
    userId?: string;
};

/**
 * (tsType: UserWithRelations, schemaOptions: { includeRelations: true })
 */
export type UserWithRelations = {
    id?: string;
    email: string;
    role?: 'admin' | 'teacher' | 'user';
    fullName?: string;
    dateOfBirth?: string;
    imagePath?: string;
    description?: string;
    academicTitle?: string;
    phoneNumber?: string;
    resetPasswordToken?: string;
    dateOfLastResetPasswordRequest?: string;
    note?: string;
    userCredentials?: UserCredentialsWithRelations;
    address?: AddressWithRelations;
    children?: Array<ChildWithRelations>;
    attendanceItems?: Array<AttendanceWithRelations>;
};

/**
 * (tsType: ChildWithRelations, schemaOptions: { includeRelations: true })
 */
export type ChildWithRelations = {
    id?: string;
    fullName: string;
    dateOfBirth: string;
    description?: string;
    monthlyFee: number;
    schoolDays: string;
    note?: string;
    users?: Array<UserWithRelations>;
    attendanceItems?: Array<AttendanceWithRelations>;
};

export type Attendance = {
    id?: string;
    date: string;
    tag: 'normal' | 'alternative';
    pickUp?: boolean;
    childId?: string;
    userId?: string;
};

/**
 * (tsType: Omit<Attendance, 'id'>, schemaOptions: { title: 'NewAttendance', exclude: [ 'id' ] })
 */
export type NewAttendance = {
    date: string;
    tag: 'normal' | 'alternative';
    pickUp?: boolean;
    childId?: string;
    userId?: string;
};

export type Action = {
    id?: string;
    imagePath?: string;
    existsFrom?: string;
    note?: string;
};

/**
 * (tsType: ActionWithRelations, schemaOptions: { includeRelations: true })
 */
export type ActionWithRelations = {
    id?: string;
    imagePath?: string;
    existsFrom?: string;
    note?: string;
};

export type LoopbackCount = {
    count?: number;
};

export type ActionControllerGetActionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionControllerGetActionResponses = {
    /**
     * Action model instance
     */
    200: ActionWithRelations;
};

export type ActionControllerGetActionResponse = ActionControllerGetActionResponses[keyof ActionControllerGetActionResponses];

export type ActionControllerGetActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions';
};

export type ActionControllerGetActionsResponses = {
    /**
     * Array of Action model instances
     */
    200: Array<ActionWithRelations>;
};

export type ActionControllerGetActionsResponse = ActionControllerGetActionsResponses[keyof ActionControllerGetActionsResponses];

export type ActionControllerDeleteActionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/actions/{id}';
};

export type ActionControllerDeleteActionResponses = {
    /**
     * Action DELETE success
     */
    204: unknown;
};

export type ActionControllerCreateActionData = {
    /**
     * Request body for multipart/form-data based file upload
     */
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/admin/actions';
};

export type ActionControllerCreateActionResponses = {
    /**
     * Action model instance
     */
    200: Action;
};

export type ActionControllerCreateActionResponse = ActionControllerCreateActionResponses[keyof ActionControllerCreateActionResponses];

export type AttendanceControllerDeleteAllAttendanceItemsOfChildData = {
    body?: never;
    path: {
        childId: string;
    };
    query?: never;
    url: '/admin/attendance/child/{childId}/items';
};

export type AttendanceControllerDeleteAllAttendanceItemsOfChildResponses = {
    /**
     * Delete all Attendance instance of the child success
     */
    204: unknown;
};

export type AttendanceControllerCreateManyChildAttendanceItemsBySchoolDaysData = {
    /**
     * Dates for creating Attendance model instances and id of the child for relation
     */
    body?: {
        childId?: string;
        from?: string;
        to?: string;
    };
    path?: never;
    query?: never;
    url: '/admin/attendance/child';
};

export type AttendanceControllerCreateManyChildAttendanceItemsBySchoolDaysResponses = {
    /**
     * Array Attendance model instances created based on school days of the child
     */
    200: Array<Attendance>;
};

export type AttendanceControllerCreateManyChildAttendanceItemsBySchoolDaysResponse = AttendanceControllerCreateManyChildAttendanceItemsBySchoolDaysResponses[keyof AttendanceControllerCreateManyChildAttendanceItemsBySchoolDaysResponses];

export type AttendanceControllerFindAttendanceData = {
    body?: never;
    path?: never;
    query?: {
        userId?: string;
        dateStr?: string;
    };
    url: '/admin/attendance/find';
};

export type AttendanceControllerFindAttendanceResponses = {
    /**
     * Attendance model instance or null if attendance doesn't exist.
     */
    200: Attendance;
};

export type AttendanceControllerFindAttendanceResponse = AttendanceControllerFindAttendanceResponses[keyof AttendanceControllerFindAttendanceResponses];

export type AttendanceControllerChangeTeacherAttendanceData = {
    /**
     * Needed date for attendance switch
     */
    body: {
        originTeacherId?: string;
        nextTeacherId?: string;
        dateStr?: string;
        isPickUp?: boolean;
    };
    path?: never;
    query?: never;
    url: '/admin/attendance/teacher/change';
};

export type AttendanceControllerChangeTeacherAttendanceResponses = {
    /**
     * Instance of Attendance model
     */
    200: Attendance;
};

export type AttendanceControllerChangeTeacherAttendanceResponse = AttendanceControllerChangeTeacherAttendanceResponses[keyof AttendanceControllerChangeTeacherAttendanceResponses];

export type AttendanceControllerDeleteAllAttendanceItemsOfUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/attendance/teacher/{userId}';
};

export type AttendanceControllerDeleteAllAttendanceItemsOfUserResponses = {
    /**
     * Instances of Attendance model of given user DELETE success
     */
    204: unknown;
};

export type AttendanceControllerCreateAttendanceItemsOfUserData = {
    /**
     * Date for creating attendance items and id representing a user
     */
    body?: {
        userId?: string;
        dates?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/admin/attendance/teacher';
};

export type AttendanceControllerCreateAttendanceItemsOfUserResponses = {
    /**
     * Array Attendandce model instances of user,
     */
    200: Array<Attendance>;
};

export type AttendanceControllerCreateAttendanceItemsOfUserResponse = AttendanceControllerCreateAttendanceItemsOfUserResponses[keyof AttendanceControllerCreateAttendanceItemsOfUserResponses];

export type AttendanceControllerDeleteAttendanceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/attendance/{id}';
};

export type AttendanceControllerDeleteAttendanceResponses = {
    /**
     * Delete Attendance instance success
     */
    204: unknown;
};

export type AttendanceControllerCreateAttendanceData = {
    body?: NewAttendance;
    path?: never;
    query?: never;
    url: '/admin/attendance';
};

export type AttendanceControllerCreateAttendanceResponses = {
    /**
     * Attendance model instance
     */
    200: Attendance;
};

export type AttendanceControllerCreateAttendanceResponse = AttendanceControllerCreateAttendanceResponses[keyof AttendanceControllerCreateAttendanceResponses];

export type ChildControllerDeleteChildData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/children/{id}';
};

export type ChildControllerDeleteChildResponses = {
    /**
     * Delete Child instance success
     */
    204: unknown;
};

export type ChildControllerCreateChildData = {
    body?: NewChild;
    path?: never;
    query?: never;
    url: '/admin/children';
};

export type ChildControllerCreateChildResponses = {
    /**
     * Child model instance
     */
    200: Child;
};

export type ChildControllerCreateChildResponse = ChildControllerCreateChildResponses[keyof ChildControllerCreateChildResponses];

export type ContactInfoControllerDeleteContactInfoData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/contactInfo/{id}';
};

export type ContactInfoControllerDeleteContactInfoResponses = {
    /**
     * ContactInfo DELETE success
     */
    204: unknown;
};

export type ContactInfoControllerUpdateContactInfoData = {
    body?: ContactInfo;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/contactInfo/{id}';
};

export type ContactInfoControllerUpdateContactInfoResponses = {
    /**
     * ContactInfo PUT success
     */
    204: unknown;
};

export type ContactInfoControllerCreateContactInfoData = {
    body?: NewContactInfo;
    path?: never;
    query?: never;
    url: '/admin/contactInfo';
};

export type ContactInfoControllerCreateContactInfoResponses = {
    /**
     * DayActivity model instance
     */
    200: ContactInfo;
};

export type ContactInfoControllerCreateContactInfoResponse = ContactInfoControllerCreateContactInfoResponses[keyof ContactInfoControllerCreateContactInfoResponses];

export type DayActivityControllerDeleteDayActivityData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/dayActivities/{id}';
};

export type DayActivityControllerDeleteDayActivityResponses = {
    /**
     * DayActivity DELETE success
     */
    204: unknown;
};

export type DayActivityControllerUpdateDayActivityData = {
    body?: DayActivity;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/dayActivities/{id}';
};

export type DayActivityControllerUpdateDayActivityResponses = {
    /**
     * DayActivity PUT success
     */
    204: unknown;
};

export type DayActivityControllerCreateDayActivityData = {
    body?: NewDayActivity;
    path?: never;
    query?: never;
    url: '/admin/dayActivities';
};

export type DayActivityControllerCreateDayActivityResponses = {
    /**
     * DayActivity model instance
     */
    200: DayActivity;
};

export type DayActivityControllerCreateDayActivityResponse = DayActivityControllerCreateDayActivityResponses[keyof DayActivityControllerCreateDayActivityResponses];

export type GeneralInfoControllerGetNextPositionOfInfoOnPageData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
    };
    url: '/admin/generalInfo/nextPosition';
};

export type GeneralInfoControllerGetNextPositionOfInfoOnPageResponses = {
    /**
     * number represents next position of info items
     */
    200: number;
};

export type GeneralInfoControllerGetNextPositionOfInfoOnPageResponse = GeneralInfoControllerGetNextPositionOfInfoOnPageResponses[keyof GeneralInfoControllerGetNextPositionOfInfoOnPageResponses];

export type GeneralInfoControllerDeleteInfoData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/generalInfo/{id}';
};

export type GeneralInfoControllerDeleteInfoResponses = {
    /**
     * GeneralInfo DELETE success
     */
    204: unknown;
};

export type GeneralInfoControllerGetInfoByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/generalInfo/{id}';
};

export type GeneralInfoControllerGetInfoByIdResponses = {
    /**
     * GeneralInfo model instance
     */
    200: GeneralInfoWithRelations;
};

export type GeneralInfoControllerGetInfoByIdResponse = GeneralInfoControllerGetInfoByIdResponses[keyof GeneralInfoControllerGetInfoByIdResponses];

export type GeneralInfoControllerUpdateInfoData = {
    body?: GeneralInfo;
    path: {
        id: number;
    };
    query?: never;
    url: '/admin/generalInfo/{id}';
};

export type GeneralInfoControllerUpdateInfoResponses = {
    /**
     * GeneralInfo PUT success
     */
    204: unknown;
};

export type GeneralInfoControllerCreateInfoData = {
    body?: NewGeneralInfo;
    path?: never;
    query?: never;
    url: '/admin/generalInfo';
};

export type GeneralInfoControllerCreateInfoResponses = {
    /**
     * GeneralInfo model instance
     */
    200: GeneralInfo;
};

export type GeneralInfoControllerCreateInfoResponse = GeneralInfoControllerCreateInfoResponses[keyof GeneralInfoControllerCreateInfoResponses];

export type ParenthoodControllerDeleteParenthoodData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/parenthood/{id}';
};

export type ParenthoodControllerDeleteParenthoodResponses = {
    /**
     * Parenthood DELETE success
     */
    204: unknown;
};

export type ParenthoodControllerGetUserParenthoodItemsData = {
    body?: never;
    path?: never;
    query?: {
        userId?: string;
    };
    url: '/admin/parenthood';
};

export type ParenthoodControllerGetUserParenthoodItemsResponses = {
    /**
     * Array of Parenthood model instances
     */
    200: Array<Parenthood>;
};

export type ParenthoodControllerGetUserParenthoodItemsResponse = ParenthoodControllerGetUserParenthoodItemsResponses[keyof ParenthoodControllerGetUserParenthoodItemsResponses];

export type ParenthoodControllerCreateParenthoodData = {
    body?: NewParenthood;
    path?: never;
    query?: never;
    url: '/admin/parenthood';
};

export type ParenthoodControllerCreateParenthoodResponses = {
    /**
     * Parenthood model instance
     */
    200: Parenthood;
};

export type ParenthoodControllerCreateParenthoodResponse = ParenthoodControllerCreateParenthoodResponses[keyof ParenthoodControllerCreateParenthoodResponses];

export type PhotoControllerDeletePhotoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/photos/{id}';
};

export type PhotoControllerDeletePhotoResponses = {
    /**
     * Photo DELETE success
     */
    204: unknown;
};

export type PhotoControllerCreatePhotoData = {
    /**
     * Request body for multipart/form-data based file upload
     */
    body: {
        file?: Blob | File;
    };
    path?: never;
    query?: {
        tag?: string;
    };
    url: '/admin/photos';
};

export type PhotoControllerCreatePhotoResponses = {
    /**
     * Photo model instance
     */
    200: Photo;
};

export type PhotoControllerCreatePhotoResponse = PhotoControllerCreatePhotoResponses[keyof PhotoControllerCreatePhotoResponses];

export type SponsorControllerUploadSponsorImageData = {
    /**
     * Request body for multipart/form-data based file upload
     */
    body: {
        file?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/sponsors/{id}/imageUpload';
};

export type SponsorControllerUploadSponsorImageResponses = {
    /**
     * Upload sponsor image success
     */
    204: unknown;
};

export type SponsorControllerDeleteSponsorData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/sponsors/{id}';
};

export type SponsorControllerDeleteSponsorResponses = {
    /**
     * Sponsor DELETE success
     */
    204: unknown;
};

export type SponsorControllerUpdateSponsorData = {
    body?: Sponsor;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/sponsors/{id}';
};

export type SponsorControllerUpdateSponsorResponses = {
    /**
     * Sponsor PUT success
     */
    204: unknown;
};

export type SponsorControllerCreateSponsorData = {
    body?: NewSponsor;
    path?: never;
    query?: never;
    url: '/admin/sponsors';
};

export type SponsorControllerCreateSponsorResponses = {
    /**
     * Sponsor model instance
     */
    200: Sponsor;
};

export type SponsorControllerCreateSponsorResponse = SponsorControllerCreateSponsorResponses[keyof SponsorControllerCreateSponsorResponses];

export type UserControllerDeleteUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type UserControllerDeleteUserResponses = {
    /**
     * User DELETE success
     */
    204: unknown;
};

export type UserControllerGetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type UserControllerGetUsersResponses = {
    /**
     * Array of User model instances
     */
    200: Array<{
        id?: string;
        email?: string;
        role?: string;
        fullName?: string;
        dateOfBirth?: string;
        description?: string;
        academicTitle?: string;
        phoneNumber?: string;
        address?: {
            id?: string;
            street?: string;
            houseNumber: string;
            city: string;
            zipCode?: string;
            note?: string;
        };
        note?: string;
        password?: string;
    }>;
};

export type UserControllerGetUsersResponse = UserControllerGetUsersResponses[keyof UserControllerGetUsersResponses];

export type AttendanceControllerEnrollNewNormalAttendanceOfChildData = {
    body?: NewAttendance;
    path?: never;
    query?: never;
    url: '/attendance/child/enroll';
};

export type AttendanceControllerEnrollNewNormalAttendanceOfChildResponses = {
    /**
     * Attendance model instance
     */
    200: Attendance;
};

export type AttendanceControllerEnrollNewNormalAttendanceOfChildResponse = AttendanceControllerEnrollNewNormalAttendanceOfChildResponses[keyof AttendanceControllerEnrollNewNormalAttendanceOfChildResponses];

export type AttendanceControllerGetCountOfAllAlternativeAttendanceItemsOfChildData = {
    body?: never;
    path: {
        childId: string;
    };
    query?: never;
    url: '/attendance/child/{childId}/alternative/count';
};

export type AttendanceControllerGetCountOfAllAlternativeAttendanceItemsOfChildResponses = {
    /**
     * Count of the alternative attendance items of the child
     */
    200: LoopbackCount;
};

export type AttendanceControllerGetCountOfAllAlternativeAttendanceItemsOfChildResponse = AttendanceControllerGetCountOfAllAlternativeAttendanceItemsOfChildResponses[keyof AttendanceControllerGetCountOfAllAlternativeAttendanceItemsOfChildResponses];

export type AttendanceControllerDeleteAllAttendanceItemsOfChildFromTodayData = {
    body?: never;
    path: {
        childId: string;
    };
    query?: never;
    url: '/attendance/child/{childId}/items/fromToday';
};

export type AttendanceControllerDeleteAllAttendanceItemsOfChildFromTodayResponses = {
    /**
     * Delete all Attendance instance of the child from today date success
     */
    204: unknown;
};

export type AttendanceControllerGetAllNormalAttendanceItemsOfChildInMonthData = {
    body?: never;
    path: {
        childId: string;
    };
    query?: {
        month?: number;
    };
    url: '/attendance/child/{childId}/normal/items';
};

export type AttendanceControllerGetAllNormalAttendanceItemsOfChildInMonthResponses = {
    /**
     * Array Attendace model instance of the child
     */
    200: Array<Attendance>;
};

export type AttendanceControllerGetAllNormalAttendanceItemsOfChildInMonthResponse = AttendanceControllerGetAllNormalAttendanceItemsOfChildInMonthResponses[keyof AttendanceControllerGetAllNormalAttendanceItemsOfChildInMonthResponses];

export type AttendanceControllerUnrollAttendanceOfChildData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attendance/child/{id}/unroll';
};

export type AttendanceControllerUnrollAttendanceOfChildResponses = {
    /**
     * Instance of Attendance model PATCH success
     */
    204: unknown;
};

export type AttendanceControllerGetAllAttendanceItemsOnDateData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
    };
    url: '/attendance/onDate';
};

export type AttendanceControllerGetAllAttendanceItemsOnDateResponses = {
    /**
     * Array Attendance model instance that exists on given date
     */
    200: Array<Attendance>;
};

export type AttendanceControllerGetAllAttendanceItemsOnDateResponse = AttendanceControllerGetAllAttendanceItemsOnDateResponses[keyof AttendanceControllerGetAllAttendanceItemsOnDateResponses];

export type AttendanceControllerGetAllAttendanceItemsOfTeachersInMonthData = {
    body?: never;
    path?: never;
    query?: {
        month?: number;
    };
    url: '/attendance/teacher/{userId}';
};

export type AttendanceControllerGetAllAttendanceItemsOfTeachersInMonthResponses = {
    /**
     * Array Attendandce model instances of user,
     */
    200: Array<Attendance>;
};

export type AttendanceControllerGetAllAttendanceItemsOfTeachersInMonthResponse = AttendanceControllerGetAllAttendanceItemsOfTeachersInMonthResponses[keyof AttendanceControllerGetAllAttendanceItemsOfTeachersInMonthResponses];

export type AttendanceControllerGetAttendanceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attendance/{id}';
};

export type AttendanceControllerGetAttendanceResponses = {
    /**
     * Attendance model instance
     */
    200: Attendance;
};

export type AttendanceControllerGetAttendanceResponse = AttendanceControllerGetAttendanceResponses[keyof AttendanceControllerGetAttendanceResponses];

export type AttendanceControllerGetAllAttendanceItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/attendance';
};

export type AttendanceControllerGetAllAttendanceItemsResponses = {
    /**
     * Array Attendance model instance
     */
    200: Array<Attendance>;
};

export type AttendanceControllerGetAllAttendanceItemsResponse = AttendanceControllerGetAllAttendanceItemsResponses[keyof AttendanceControllerGetAllAttendanceItemsResponses];

export type AuthControllerForgotPasswordData = {
    /**
     * email of user who forgot password
     */
    body: {
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/forgotPassword';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Request of forgotten password success
     */
    204: unknown;
};

export type AuthControllerResetPasswordData = {
    /**
     * new password
     */
    body: {
        password?: string;
    };
    path: {
        token: string;
    };
    query?: never;
    url: '/auth/resetPassword/{token}';
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Reset password success
     */
    204: unknown;
};

export type ChildControllerGetChildrenWithAttendanceOnDateData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
    };
    url: '/children/attendanceOnDate';
};

export type ChildControllerGetChildrenWithAttendanceOnDateResponses = {
    /**
     * Array of Child model instances that has attendance on given date.
     */
    200: Array<Child>;
};

export type ChildControllerGetChildrenWithAttendanceOnDateResponse = ChildControllerGetChildrenWithAttendanceOnDateResponses[keyof ChildControllerGetChildrenWithAttendanceOnDateResponses];

export type ChildControllerGetChildParentsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/children/{id}/parents';
};

export type ChildControllerGetChildParentsResponses = {
    /**
     * Array User model instance
     */
    200: Array<UserWithRelations>;
};

export type ChildControllerGetChildParentsResponse = ChildControllerGetChildParentsResponses[keyof ChildControllerGetChildParentsResponses];

export type ChildControllerGetChildData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/children/{id}';
};

export type ChildControllerGetChildResponses = {
    /**
     * Child model instance
     */
    200: Child;
};

export type ChildControllerGetChildResponse = ChildControllerGetChildResponses[keyof ChildControllerGetChildResponses];

export type ChildControllerUpdateChildData = {
    body?: Child;
    path: {
        id: string;
    };
    query?: never;
    url: '/children/{id}';
};

export type ChildControllerUpdateChildResponses = {
    /**
     * update Child success
     */
    204: unknown;
};

export type ChildControllerGetChildrenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/children';
};

export type ChildControllerGetChildrenResponses = {
    /**
     * Array of child model instances
     */
    200: Array<ChildWithRelations>;
};

export type ChildControllerGetChildrenResponse = ChildControllerGetChildrenResponses[keyof ChildControllerGetChildrenResponses];

export type ContactInfoControllerGetOneContactInfoData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contactInfo/{id}';
};

export type ContactInfoControllerGetOneContactInfoResponses = {
    /**
     * ContactInfo model instance
     */
    200: ContactInfoWithRelations;
};

export type ContactInfoControllerGetOneContactInfoResponse = ContactInfoControllerGetOneContactInfoResponses[keyof ContactInfoControllerGetOneContactInfoResponses];

export type ContactInfoControllerGetAllContactInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contactInfo';
};

export type ContactInfoControllerGetAllContactInfoResponses = {
    /**
     * Array of ContactInfo model instances
     */
    200: Array<ContactInfoWithRelations>;
};

export type ContactInfoControllerGetAllContactInfoResponse = ContactInfoControllerGetAllContactInfoResponses[keyof ContactInfoControllerGetAllContactInfoResponses];

export type DayActivityControllerGetDayActivityData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/dayActivities/{id}';
};

export type DayActivityControllerGetDayActivityResponses = {
    /**
     * DayActivity model instance
     */
    200: DayActivityWithRelations;
};

export type DayActivityControllerGetDayActivityResponse = DayActivityControllerGetDayActivityResponses[keyof DayActivityControllerGetDayActivityResponses];

export type DayActivityControllerGetAllDayActivitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dayActivities';
};

export type DayActivityControllerGetAllDayActivitiesResponses = {
    /**
     * Array of DayActivity model instances
     */
    200: Array<DayActivityWithRelations>;
};

export type DayActivityControllerGetAllDayActivitiesResponse = DayActivityControllerGetAllDayActivitiesResponses[keyof DayActivityControllerGetAllDayActivitiesResponses];

export type GeneralInfoControllerGetInfoData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
    };
    url: '/generalInfo';
};

export type GeneralInfoControllerGetInfoResponses = {
    /**
     * Array of GeneralInfo model instances
     */
    200: Array<GeneralInfoWithRelations>;
};

export type GeneralInfoControllerGetInfoResponse = GeneralInfoControllerGetInfoResponses[keyof GeneralInfoControllerGetInfoResponses];

export type PaymentControllerGeneratePaymentQrData = {
    body?: never;
    path?: never;
    query?: {
        amount?: number;
        variableSymbol?: string;
        accountNumber?: string;
        message?: string;
        returnType?: string;
    };
    url: '/payment/qr';
};

export type PaymentControllerGeneratePaymentQrResponses = {
    /**
     * Generate payment QR
     */
    200: string;
};

export type PaymentControllerGeneratePaymentQrResponse = PaymentControllerGeneratePaymentQrResponses[keyof PaymentControllerGeneratePaymentQrResponses];

export type PhotoControllerGetPhotoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/photos/{id}';
};

export type PhotoControllerGetPhotoResponses = {
    /**
     * Photo model instance
     */
    200: PhotoWithRelations;
};

export type PhotoControllerGetPhotoResponse = PhotoControllerGetPhotoResponses[keyof PhotoControllerGetPhotoResponses];

export type PhotoControllerGetPhotosData = {
    body?: never;
    path?: never;
    query?: {
        tag?: string;
    };
    url: '/photos';
};

export type PhotoControllerGetPhotosResponses = {
    /**
     * Array of Photo model instances
     */
    200: Array<PhotoWithRelations>;
};

export type PhotoControllerGetPhotosResponse = PhotoControllerGetPhotosResponses[keyof PhotoControllerGetPhotosResponses];

export type SponsorControllerGetSponsorData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type SponsorControllerGetSponsorResponses = {
    /**
     * Sponsor model instance
     */
    200: SponsorWithRelations;
};

export type SponsorControllerGetSponsorResponse = SponsorControllerGetSponsorResponses[keyof SponsorControllerGetSponsorResponses];

export type SponsorControllerGetSponsorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type SponsorControllerGetSponsorsResponses = {
    /**
     * Array of Sponsor model instances
     */
    200: Array<SponsorWithRelations>;
};

export type SponsorControllerGetSponsorsResponse = SponsorControllerGetSponsorsResponses[keyof SponsorControllerGetSponsorsResponses];

export type UserControllerLoginData = {
    /**
     * The input of login function
     */
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users/login';
};

export type UserControllerLoginResponses = {
    /**
     * Token
     */
    200: {
        token?: string;
    };
};

export type UserControllerLoginResponse = UserControllerLoginResponses[keyof UserControllerLoginResponses];

export type UserControllerSignupData = {
    /**
     * Data for signup user
     */
    body: {
        email: string;
        role: string;
        fullName: string;
        dateOfBirth?: string;
        description?: string;
        academicTitle?: string;
        phoneNumber: string;
        address: {
            street?: string;
            houseNumber: string;
            city: string;
            zipCode?: string;
            note?: string;
        };
        note?: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users/signup';
};

export type UserControllerSignupResponses = {
    /**
     * User
     */
    200: User;
};

export type UserControllerSignupResponse = UserControllerSignupResponses[keyof UserControllerSignupResponses];

export type UserControllerGetWorkingTeachersOnDateData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
    };
    url: '/users/teachers/onDate';
};

export type UserControllerGetWorkingTeachersOnDateResponses = {
    /**
     * Array of User model instances that works on given date.
     */
    200: Array<User>;
};

export type UserControllerGetWorkingTeachersOnDateResponse = UserControllerGetWorkingTeachersOnDateResponses[keyof UserControllerGetWorkingTeachersOnDateResponses];

export type UserControllerGetTeachersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/teachers';
};

export type UserControllerGetTeachersResponses = {
    /**
     * Array of User model instances
     */
    200: Array<User>;
};

export type UserControllerGetTeachersResponse = UserControllerGetTeachersResponses[keyof UserControllerGetTeachersResponses];

export type UserControllerWhoAmIData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/whoAmI';
};

export type UserControllerWhoAmIResponses = {
    /**
     * Return current user
     */
    200: string;
};

export type UserControllerWhoAmIResponse = UserControllerWhoAmIResponses[keyof UserControllerWhoAmIResponses];

export type UserControllerUpdateUserAddressData = {
    body?: Address;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/address';
};

export type UserControllerUpdateUserAddressResponses = {
    /**
     * User PUT success
     */
    204: unknown;
};

export type UserControllerChangeUserPasswordData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/changePassword';
};

export type UserControllerChangeUserPasswordResponses = {
    /**
     * Change and save user password SUCCESS.
     */
    204: unknown;
};

export type UserControllerGetChidrenData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/children';
};

export type UserControllerGetChidrenResponses = {
    /**
     * Array of Child model instances
     */
    200: Array<Child>;
};

export type UserControllerGetChidrenResponse = UserControllerGetChidrenResponses[keyof UserControllerGetChidrenResponses];

export type UserControllerUploadUserImageData = {
    /**
     * Request body for multipart/form-data based file upload
     */
    body: {
        file?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/imageUpload';
};

export type UserControllerUploadUserImageResponses = {
    /**
     * Upload user image success
     */
    204: unknown;
};

export type UserControllerGetUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerGetUserResponses = {
    /**
     * User model instance
     */
    200: {
        id?: string;
        email?: string;
        role?: string;
        fullName?: string;
        dateOfBirth?: string;
        description?: string;
        academicTitle?: string;
        phoneNumber?: string;
        address?: {
            id?: string;
            street?: string;
            houseNumber: string;
            city: string;
            zipCode?: string;
            note?: string;
        };
        note?: string;
        password?: string;
    };
};

export type UserControllerGetUserResponse = UserControllerGetUserResponses[keyof UserControllerGetUserResponses];

export type UserControllerUpdateUserData = {
    body?: User;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerUpdateUserResponses = {
    /**
     * User PUT success
     */
    204: unknown;
};

export type ClientOptions = {
    baseURL: 'https://api.pojdteven.workbox.cz' | (string & {});
};